#!/bin/bash

# $Id$


#----------------------------------#
blfs_tool_clean_scripts() {        # Remove unselected dependencies scripts
#----------------------------------#

  for file in ${PROGNAME}-commands/blfs-tool-deps/* ; do
    # Keep the script file name
    this_script=`basename $file`

    case "${this_script}" in
          *libxml2 ) [[ "${DEP_LIBXML}" = "n" ]]  && rm ${file} ;;
          *libxslt ) [[ "${DEP_LIBXSLT}" = "n" ]] && rm ${file} ;;
             *tidy ) [[ "${DEP_TIDY}" = "n" ]]    && rm ${file} ;;
            *unzip ) [[ "${DEP_UNZIP}" = "n" ]]   && rm ${file} ;;
      *docbook-xml ) [[ "${DEP_DBXML}" = "n" ]]   && rm ${file} ;;
      *docbook-xsl ) [[ "${DEP_DBXSL}" = "n" ]]   && rm ${file} ;;
              *gpm ) [[ "${DEP_GPM}" = "n" ]]     && rm ${file} ;;
             *lynx ) [[ "${DEP_LYNX}" = "n" ]]    && rm ${file} ;;
             *sudo ) [[ "${DEP_SUDO}" = "n" ]]    && rm ${file} ;;
             *wget ) [[ "${DEP_WGET}" = "n" ]]    && rm ${file} ;;
       *subversion ) [[ "${DEP_SVN}" = "n" ]]     && rm ${file} ;;
    esac
  done
}


#----------------------------------#
wrt_blfs_tool_targets() {          #
#----------------------------------#
  PREV=""

  echo "${tab_}${GREEN}Processing... ${L_arrow}BLFS_TOOL ${R_arrow}"

  for file in blfs-tool-deps/* ; do
    # Keep the script file name
    this_script=`basename $file`

    # Grab the phase name to be used with INSTALL_LOG and tracking dir touch
    name=`grep "^PKG_PHASE=" ${file} | sed -e 's@PKG_PHASE=@@'`
    # Grab also the package version
    pkg_ver=`grep "^VERSION=" ${file} | sed -e 's@VERSION=@@'`

    # Append each name of the script files to a list (this will become
    # the names of the targets in the Makefile)
    blfs_tool="$blfs_tool ${this_script}"

    #--------------------------------------------------------------------#
    #         >>>>>>>> START BUILDING A Makefile ENTRY <<<<<<<<          #
    #--------------------------------------------------------------------#
    #
    # Drop in the name of the target on a new line, and the previous target
    # as a dependency. Also call the echo_message function.
    wrt_target "${this_script}" "$PREV"

    # Touch timestamp file if installed files logs will be created.
    if [ "$name" != "" ] && [ "${INSTALL_LOG}" = "y" ] ; then
      wrt_TouchTimestamp
    fi

    # Run the script.
    wrt_RunScript "$file"

    # Write installed files log
    if [ "$name" != "" ] && [ "${INSTALL_LOG}" = "y" ] ; then
      wrt_LogNewFiles "$name"
    fi

    # Touch the tracking file.
    if [ "$PROGNAME" = "clfs2" ]; then
      echo -e "\t@touch \$(MOUNT_PT)$TRACKING_DIR/${name}-${pkg_ver}" >>  $MKFILE.tmp
    else
      echo -e "\t@touch $TRACKING_DIR/${name}-${pkg_ver}" >>  $MKFILE.tmp
    fi

    # Include a touch of the target name so make can check
    # if it's already been made.
    wrt_touch
    #
    #--------------------------------------------------------------------#
    #              >>>>>>>> END OF Makefile ENTRY <<<<<<<<               #
    #--------------------------------------------------------------------#

    # Keep the script file name for Makefile dependencies.
    PREV=${this_script}
  done
}
