#!/bin/bash

# $Id$

set -e
cd $PKGDIR
./configure --prefix=/usr
make
if ! [ -z $PKG_DEST ]; then
	mkdir -pv $PKG_DEST/{lib,usr/{share/{man,doc,info},lib}}
	ln -sv share/{man,doc,info} $PKG_DEST/usr
	case $(uname -m) in
	 x86_64) ln -sv lib $PKG_DEST/lib64 && ln -sv lib $PKG_DEST/usr/lib64 ;;
	esac
fi
make DESTDIR=$PKG_DEST install
if ! [ -z $PKG_DEST ]; then 
	rm -fv $PKG_DEST/{,usr/}lib64 
	rm -fv $PKG_DEST/usr/{man,doc,info}
        for dir in $PKG_DEST/usr/share/{doc,info,man}; do
          [[ -z $(ls $dir) ]] && rmdir -v $dir
        done
        for dir in $PKG_DEST/usr/{lib,share}; do
          [[ -z $(ls $dir) ]] && rmdir -v $dir
        done
        for dir in $PKG_DEST/{lib,usr}; do
          [[ -z $(ls $dir) ]] && rmdir -v $dir
        done
	packInstall
fi
rm -rf $PKG_DEST

exit
