#!/bin/sh

# $Id$

set -e
cd $PKGDIR

install -v -m755 -d /usr/share/xml/docbook/xsl-stylesheets-1.69.1
cp -v -R VERSION common eclipse extensions fo html \
         htmlhelp images javahelp lib manpages params \
         profiling slides template website xhtml \
    /usr/share/xml/docbook/xsl-stylesheets-1.69.1

if [ ! -d /etc/xml ]; then install -v -m755 -d /etc/xml; fi
if [ ! -f /etc/xml/catalog ]; then
    xmlcatalog --noout --create /etc/xml/catalog
fi

xmlcatalog --noout --add "rewriteSystem" \
           "http://docbook.sourceforge.net/release/xsl/1.69.1" \
           "/usr/share/xml/docbook/xsl-stylesheets-1.69.1" \
    /etc/xml/catalog

xmlcatalog --noout --add "rewriteURI" \
           "http://docbook.sourceforge.net/release/xsl/1.69.1" \
           "/usr/share/xml/docbook/xsl-stylesheets-1.69.1" \
    /etc/xml/catalog

xmlcatalog --noout --add "rewriteSystem" \
           "http://docbook.sourceforge.net/release/xsl/current" \
           "/usr/share/xml/docbook/xsl-stylesheets-1.69.1" \
    /etc/xml/catalog

xmlcatalog --noout --add "rewriteURI" \
           "http://docbook.sourceforge.net/release/xsl/current" \
           "/usr/share/xml/docbook/xsl-stylesheets-1.69.1" \
    /etc/xml/catalog

exit
