#!/bin/sh

# $Id$

set -e
cd $PKGDIR

./configure --prefix=/usr \
            --without-berkeley-db \
            --with-installbuilddir=/usr/lib/apr-0
make
make install
rm doc/{Makefile,doxygen.conf}
find doc -type d -exec chmod 755 {} \;
find doc -type f -exec chmod 644 {} \;
install -v -m755 -d /usr/share/doc/subversion-1.3.1
cp -v -R doc/* /usr/share/doc/subversion-1.3.1

exit
