#!/bin/bash
# $Id$

# Acknowledgment:
#  The following code is a modified version of an original work written by
#  Greg Schafer for the "DIY Linux" project and is included here with his
#  permission.
#  ref: http://www.diy-linux.org
#

set -e

local RAWDIFF=/tmp/rawdiff.$$
local REPORT="${3}/REPORT.${1}V${2}"

cd $4

echo -e "Diffing ${1} and ${2}... " > $REPORT
diff -ur ${1} ${2} > $RAWDIFF || :

echo -e "The list of binary files that differ:\n" > $REPORT
grep "iles.*differ$" $RAWDIFF >> $REPORT

echo -e "The list of files that exist \"only in\" 1 of the directories:\n" >> $REPORT

if grep "^Only in" $RAWDIFF >/dev/null 2>&1; then
  grep "^Only in" $RAWDIFF >> $REPORT
else
  echo NONE >> $REPORT
fi

grep -v "iles.*differ$" $RAWDIFF | \
grep -v "^Only in" > ${ICA_DIR}/${1}V${2}.ASCII.DIFF

rm -f $RAWDIFF
